### PR TITLE
Add isomorphic ability

### PR DESCRIPTION
**Pull request by jsguy**
Hi @ArthurClemens !

I've added isomorphic ability as discussed - I've only had to make minimal changes to about 20 or so files - they all use common/isomorphic.es6, which knows if we're on a client or server, a very basic check.

I know there's > 300 files in the PR, but other than those 20 changes, they're all generated - let me know if you'd prefer just the changed files, instead of all the generated stuff as well?

### CODE REVIEW

**Comment by ArthurClemens** [comment]
Thanks for the PR! I will have a look at it the coming days.

**Comment by jsguy** [comment]
Hi @ArthurClemens I've found and fixed a few small things - I was thinking we can easily add the fixes after the merge, or would you like a fresh pull request straight away?

**Comment by ArthurClemens** [comment]
No worries, later changes get included in a PR. I will have time this weekend to review.

I forgot - how do I test the code? Using [mithril-node-render](https://github.com/StephanHoyer/mithril-node-render)?

**Comment by jsguy** [comment]
Yes exactly - here's some code to get you started:

```javascript
var assert = require('assert'),
	m = require('mithril'),
	render = require('mithril-node-render'),
	snackbar = require('polythene/notification/snackbar'),
	button = require('polythene/button/button');

var button1 = render([
	m.component(button, {
		label: 'Show',
		raised: true,
		events: {
			onclick: function() {
				snackbar.show({
					containerSelector: '#snackbar',
					title: 'This message tells some things using quite a few words.'
				});
			}
		}
	}),
	m('#snackbar', m.component(snackbar))
]);

var expectedButton1 = '<a class="pe-button pe-button--text     pe-button--raised  " id="" tabindex="0"><div class="pe-button__content"><div class="pe-shadow pe-shadow--animated " id=""><div class="pe-shadow__bottom pe-shadow--z-1"></div><div class="pe-shadow__top pe-shadow--z-1"></div></div><div class="pe-ripple pe-ripple--constrained " id=""><div class="pe-ripple__mask"><div class="pe-ripple__waves"></div></div></div><div class="pe-button__wash"></div><div class="pe-button__focus"></div><div class="pe-button__label">Show</div></div></a><div id="snackbar"><span class="pe-snackbar__placeholder"></span></div>';

assert(button1 === expectedButton1, "We have HTML for a button");
```

So that assertion should pass.

**Comment by jsguy** [comment]
You'll need these:

```javascript
"devDependencies": {
	"mithril": "^0.2.5",
	"mithril-node-render": "^0.5.2",
	"ploythene": "git://github.com/jsguy/polythene.git"
}
```

**Comment by ArthurClemens** [comment]
In my Jest tests the button component gets rendered normally (see https://github.com/ArthurClemens/polythene/blob/master/button/__tests__/__snapshots__/button-serverside.spec.js.snap), before having made code changes. How do I create a failure case?

**Comment by jsguy** [comment]
It should fail on Line 25:

```javascript
-const startType = window.PointerEvent ? 'pointerdown' : (('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch) ? 'touchstart' : 'mousedown';		
```
https://github.com/ArthurClemens/polythene/pull/39/files#diff-71c866e942e8003c800aab74821b972eL25

`window` is undefined in node, unless you've created a mock window object yourself?

**Comment by ArthurClemens** [comment]
Ah, Jest includes jsdom. I'll try to setup the tests in a different way.

**Comment by jsguy** [comment]
Ah, that makes sense :)

**Comment by jsguy** [comment]
@ArthurClemens I see you've made great progress with the [rewrite](https://github.com/ArthurClemens/polythene/tree/rewrite/) - do you think it is in a state where I can add isomorphism to it now, or should I wait a little?

**Comment by ArthurClemens** [comment]
Yes, a PR is welcome. Note that the test environment is a bit of a mess (I want to migrate from Rollup to Webpack) but running the tests `run npm test:watch` should work.

**Comment by jsguy** [comment]
Hi @ArthurClemens Are you waiting for me to do something with this?

**Comment by ArthurClemens** [comment]
I am still having problems getting the backend tests running on master. At the same time I am focusing my attention to the rewrite, as I have still a couple of components to go. I will need to bring over your changes to the rewrite branch - and that will not be a simple copy & paste :-(

**Comment by jsguy** [comment]
Ok, I'll see if I can move my framework to using the rewrite instead - that is the way forward anyway - I don't think there will be many other users of isomorphism in the old version ;)

**Comment by ArthurClemens** [comment]
Implemented with cc3713eaa99901fda1d243a20a60ecad6176a71f
Thanks!

**Pull request closed without merging**
